services:
  - type: web
    name: desi-premium-1
    env: node
    plan: free
    buildCommand: npm install && npm install --prefix client && npm run build --prefix client && npm install --prefix server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000

